services:
  organizations:
    url: organizations:3000
    user:
      routes:
        - path: /api/organizations
          methods: [POST, GET]
        - path: /api/organizations/{organization_id}
          methods: [GET, PATCH, DELETE]
        - path: /api/organizations/{organization_id}/members
          methods: [GET, POST]
        - path: /api/organizations/{organization_id}/members/{member_id}
          methods: [GET, PATCH, DELETE]
